package main

import (
	"flag"
	"fmt"
	"html"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"wijnberg.net/vsdx-go/vsdx"
)

type CompareResult struct {
	Name      string
	GoldenSVG string
	NewSVG    string
	NewErr    string
}

func main() {
	inputDir := flag.String("input", "vsdx-svg", "directory with VSDX/SVG pairs")
	outputDir := flag.String("output", "render-compare-output", "output directory")
	flag.Parse()

	// Create output directory
	if err := os.MkdirAll(*outputDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output dir: %v\n", err)
		os.Exit(1)
	}

	// Find all VSDX files
	vsdxFiles, err := filepath.Glob(filepath.Join(*inputDir, "*.vsdx"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding VSDX files: %v\n", err)
		os.Exit(1)
	}

	var results []CompareResult

	for _, vsdxPath := range vsdxFiles {
		baseName := strings.TrimSuffix(filepath.Base(vsdxPath), ".vsdx")
		svgPath := filepath.Join(*inputDir, baseName+".svg")

		// Check if golden SVG exists
		if _, err := os.Stat(svgPath); os.IsNotExist(err) {
			fmt.Printf("Skipping %s (no matching SVG)\n", baseName)
			continue
		}

		result := processFile(baseName, vsdxPath, svgPath)
		results = append(results, result)

		// Copy golden SVG to output
		goldenData, _ := os.ReadFile(svgPath)
		os.WriteFile(filepath.Join(*outputDir, baseName+"_golden.svg"), goldenData, 0644)

		// Write rendered SVG
		if result.NewErr == "" {
			os.WriteFile(filepath.Join(*outputDir, baseName+"_rendered.svg"), []byte(result.NewSVG), 0644)
		}

		fmt.Printf("Processed: %s\n", baseName)
	}

	// Write HTML comparison
	htmlPath := filepath.Join(*outputDir, "compare.html")
	if err := writeHTML(results, htmlPath); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing HTML: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("\nOutput written to: %s/\n", *outputDir)
}

// extractPageNumber parses the golden SVG to find which page it was exported from.
// Returns 0-based index. Defaults to 0 if not found.
func extractPageNumber(goldenSVG string) int {
	// Look for "Page-N" in Visio's SVG comment: <!-- Generated by Microsoft Visio, SVG Export ... Page-2 -->
	re := regexp.MustCompile(`Page-(\d+)`)
	matches := re.FindStringSubmatch(goldenSVG)
	if len(matches) >= 2 {
		var pageNum int
		fmt.Sscanf(matches[1], "%d", &pageNum)
		return pageNum - 1 // Convert to 0-based index
	}
	return 0
}

func processFile(name, vsdxPath, svgPath string) CompareResult {
	result := CompareResult{Name: name}

	// Load golden SVG
	goldenData, err := os.ReadFile(svgPath)
	if err != nil {
		result.GoldenSVG = fmt.Sprintf("Error: %v", err)
	} else {
		result.GoldenSVG = string(goldenData)
	}

	// Load VSDX
	vf, err := vsdx.Open(vsdxPath)
	if err != nil {
		result.NewErr = fmt.Sprintf("VSDX load error: %v", err)
		return result
	}
	defer vf.Close()

	if len(vf.Pages) == 0 {
		result.NewErr = "No pages in VSDX"
		return result
	}

	// Determine which page to render based on golden SVG
	pageIndex := extractPageNumber(result.GoldenSVG)
	if pageIndex >= len(vf.Pages) {
		pageIndex = 0
	}
	page := vf.Pages[pageIndex]
	pageW := page.Width()
	pageH := page.Height()
	if pageW == 0 {
		pageW = 800
	}
	if pageH == 0 {
		pageH = 600
	}

	// Render with RenderTree renderer
	newSVG, newErr := renderPageNew(page, pageW, pageH)
	if newErr != nil {
		result.NewErr = newErr.Error()
	} else {
		result.NewSVG = newSVG
	}

	return result
}

func renderPageNew(page *vsdx.Page, pageW, pageH float64) (string, error) {
	var sb strings.Builder

	// Use 72 pixels per inch for scaling
	ppi := 72.0
	viewW := pageW * ppi
	viewH := pageH * ppi

	sb.WriteString(fmt.Sprintf(`<svg xmlns="http://www.w3.org/2000/svg" width="%.4fin" height="%.4fin" viewBox="0 0 %.2f %.2f">`, pageW, pageH, viewW, viewH))
	sb.WriteString("\n")

	for _, shape := range page.ChildShapes() {
		shapeW := shape.Width()
		shapeH := shape.Height()
		shapeAngle := shape.Angle()

		// Check if this is a rotated 1D shape (like a divider line or connector)
		// These have Height=0 and non-zero Angle, and use BeginX/BeginY for positioning
		isRotated1D := shapeH == 0 && shapeAngle != 0

		if isRotated1D {
			// For rotated 1D shapes, draw the line directly using BeginX/BeginY/EndX/EndY
			// This avoids complex rotation transforms
			x1 := shape.BeginX() * ppi
			y1 := (pageH - shape.BeginY()) * ppi
			x2 := shape.EndX() * ppi
			y2 := (pageH - shape.EndY()) * ppi

			// Get line color from effective style
			style := shape.ComputeEffectiveStyle()
			lineColor := style.EffectiveLineColor()
			if lineColor == "" {
				lineColor = "#000000"
			}

			// Get line style from effective style (already computed above)
			linePattern := style.LinePattern
			strokeWidth := style.LineWeight // already in points

			// Generate dash array for line pattern
			dashArray := ""
			if linePattern == 4 { // Dash-Dot
				dashArray = fmt.Sprintf(`stroke-dasharray="%.2f %.2f %.2f %.2f"`,
					strokeWidth*7, strokeWidth*5, 0.0, strokeWidth*5)
			}

			// Check for arrow markers from effective style
			endArrow := style.EndArrow
			beginArrow := style.BeginArrow
			hasEndArrow := endArrow > 0
			hasBeginArrow := beginArrow > 0

			if hasEndArrow || hasBeginArrow {
				// Calculate marker size based on arrow size and stroke width
				// Same formula as render_tree.go createMarkerDef
				arrowSizeMultipliers := []float64{0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0}
				sizeMult := 1.0
				if style.EndArrowSize >= 0 && style.EndArrowSize < len(arrowSizeMultipliers) {
					sizeMult = arrowSizeMultipliers[style.EndArrowSize]
				}
				baseScale := 0.36 * sizeMult
				minVisualWidth := 7.0 * sizeMult
				baseVisualWidth := 10 * baseScale * strokeWidth
				var markerSize float64
				if baseVisualWidth >= minVisualWidth {
					markerSize = 10 * baseScale
				} else {
					markerSize = minVisualWidth / strokeWidth
				}

				// Use path with markers for connectors with arrows
				markerID := fmt.Sprintf("arrow_%s_%s", strings.ReplaceAll(lineColor, "#", ""), shape.ID)

				// Build marker defs
				sb.WriteString("<defs>\n")
				if hasEndArrow {
					sb.WriteString(fmt.Sprintf(`  <marker id="%s_end" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="%.2f" markerHeight="%.2f" markerUnits="strokeWidth" orient="auto"><path d="M0 0 L10 5 L0 10 z" fill="%s" stroke="none"/></marker>`,
						markerID, markerSize, markerSize, lineColor))
					sb.WriteString("\n")
				}
				if hasBeginArrow {
					sb.WriteString(fmt.Sprintf(`  <marker id="%s_start" viewBox="0 0 10 10" refX="0" refY="5" markerWidth="%.2f" markerHeight="%.2f" markerUnits="strokeWidth" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10 z" fill="%s" stroke="none"/></marker>`,
						markerID, markerSize, markerSize, lineColor))
					sb.WriteString("\n")
				}
				sb.WriteString("</defs>\n")

				// Build marker-end/start attributes
				markerAttrs := ""
				if hasBeginArrow {
					markerAttrs += fmt.Sprintf(` marker-start="url(#%s_start)"`, markerID)
				}
				if hasEndArrow {
					markerAttrs += fmt.Sprintf(` marker-end="url(#%s_end)"`, markerID)
				}

				sb.WriteString(fmt.Sprintf(`<path d="M%.2f %.2fL%.2f %.2f" fill="none" stroke="%s" stroke-width="%.2f" %s stroke-linecap="round"%s/>`,
					x1, y1, x2, y2, lineColor, strokeWidth, dashArray, markerAttrs))
			} else {
				// Simple line without arrows
				sb.WriteString(fmt.Sprintf(`<line x1="%.2f" y1="%.2f" x2="%.2f" y2="%.2f" stroke="%s" stroke-width="%.2f" %s stroke-linecap="round"/>`,
					x1, y1, x2, y2, lineColor, strokeWidth, dashArray))
			}
			sb.WriteString("\n")
			continue
		}

		if shapeW == 0 {
			shapeW = 1
		}
		if shapeH == 0 {
			shapeH = 1
		}

		// Render shape at its pixel size
		pixelW := math.Abs(shapeW) * ppi
		pixelH := math.Abs(shapeH) * ppi

		result, err := vsdx.ShapeToSVG(shape,
			vsdx.WithSize(pixelW, pixelH),
			vsdx.WithPrecision(2))
		if err != nil {
			continue
		}

		// Extract inner SVG content and position it
		inner := extractSVGContent(string(result.SVG))

		// Position in page coordinates (converted to pixels)
		// PinX/PinY is the shape's center, LocPinX/LocPinY is the local center offset
		x := (shape.X() - shape.LocX()) * ppi
		// For negative height shapes, LocY is also negative, so use shape.Y() - LocY for top edge
		var y float64
		if shapeH < 0 {
			// Negative height: shape is flipped, top edge is at Y - LocY
			y = viewH - (shape.Y()-shape.LocY())*ppi
		} else {
			y = viewH - (shape.Y()+(shape.Height()-shape.LocY()))*ppi
		}

		sb.WriteString(fmt.Sprintf(`<g transform="translate(%.2f %.2f)">`, x, y))
		sb.WriteString(inner)
		sb.WriteString("</g>\n")
	}

	sb.WriteString("</svg>\n")
	return sb.String(), nil
}

func extractSVGContent(svg string) string {
	// Remove XML declaration and SVG wrapper, keep inner content
	svg = strings.TrimSpace(svg)

	// Find opening <svg> tag end
	start := strings.Index(svg, ">")
	if start == -1 {
		return svg
	}

	// Find closing </svg>
	end := strings.LastIndex(svg, "</svg>")
	if end == -1 {
		return svg[start+1:]
	}

	return svg[start+1 : end]
}

func writeHTML(results []CompareResult, path string) error {
	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>VSDX Renderer Comparison</title>
<style>
body {
	font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
	margin: 0;
	padding: 20px;
	background: #f5f5f5;
}
h1 { margin: 0 0 10px; }
p.subtitle { color: #666; margin: 0 0 20px; }
.fixture {
	background: white;
	border-radius: 8px;
	padding: 20px;
	margin-bottom: 20px;
	box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}
.fixture-name {
	font-size: 18px;
	font-weight: 600;
	margin: 0 0 15px;
}
.compare-grid {
	display: grid;
	grid-template-columns: repeat(2, 1fr);
	gap: 15px;
}
.svg-panel {
	border: 1px solid #ddd;
	border-radius: 4px;
	overflow: hidden;
}
.svg-panel-header {
	padding: 8px 12px;
	border-bottom: 1px solid #ddd;
	font-weight: 500;
	font-size: 14px;
}
.svg-panel-header.golden { background: #e8f5e9; color: #2e7d32; }
.svg-panel-header.rendered { background: #e3f2fd; color: #1565c0; }
.svg-container {
	padding: 10px;
	background: white;
	min-height: 400px;
	overflow: auto;
}
.svg-container svg {
	width: 100%;
	height: auto;
}
.svg-container object {
	width: 100%;
	height: 500px;
}
.error {
	color: #c62828;
	padding: 10px;
	background: #ffebee;
	font-family: monospace;
	font-size: 12px;
}
</style>
</head>
<body>
<h1>VSDX Renderer Comparison</h1>
<p class="subtitle">Golden (Visio export) vs vsdx-go RenderTree</p>
`)

	for _, r := range results {
		sb.WriteString(fmt.Sprintf(`<div class="fixture">
<h2 class="fixture-name">%s</h2>
<div class="compare-grid">
`, html.EscapeString(r.Name)))

		// Golden panel - use object tag to load external SVG
		sb.WriteString(fmt.Sprintf(`<div class="svg-panel">
<div class="svg-panel-header golden">Golden (Visio)</div>
<div class="svg-container">
<object type="image/svg+xml" data="%s_golden.svg">Golden SVG</object>
</div>
</div>
`, r.Name))

		// Rendered panel
		sb.WriteString(`<div class="svg-panel">
<div class="svg-panel-header rendered">vsdx-go</div>
<div class="svg-container">
`)
		if r.NewErr != "" {
			sb.WriteString(fmt.Sprintf(`<div class="error">%s</div>`, html.EscapeString(r.NewErr)))
		} else {
			sb.WriteString(fmt.Sprintf(`<object type="image/svg+xml" data="%s_rendered.svg">Rendered SVG</object>`, r.Name))
		}
		sb.WriteString(`</div></div>
`)

		sb.WriteString(`</div></div>
`)
	}

	sb.WriteString(`</body></html>`)

	return os.WriteFile(path, []byte(sb.String()), 0644)
}
